// <auto-generated />
using System;
using AuditorioTickets.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditorioTickets.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917174954_IndiceExpiracionBoletos")]
    partial class IndiceExpiracionBoletos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AuditorioTickets.Api.Domain.Boleto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoQrBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompradorEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompradorNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoPagoPreferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPagado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("MercadoPagoPaymentId");

                    b.HasIndex("MercadoPagoPreferenceId");

                    b.HasIndex("Estado", "FechaCreacion");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("AuditorioTickets.Api.Domain.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntradasReservadas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradasVendidas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaEvento");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CapacidadMaxima = 300,
                            ConcurrencyStamp = new Guid("f8377385-4a25-43b3-bcd8-da115c07ed00"),
                            Descripcion = "Ceremonia de graduación de la promoción 2026",
                            EntradasReservadas = 0,
                            EntradasVendidas = 0,
                            FechaEvento = new DateTime(2026, 12, 15, 18, 0, 0, 0, DateTimeKind.Utc),
                            Lugar = "Auditorio Central",
                            Precio = 2500m,
                            Titulo = "Acto de Colación 2026"
                        });
                });

            modelBuilder.Entity("AuditorioTickets.Api.Domain.Boleto", b =>
                {
                    b.HasOne("AuditorioTickets.Api.Domain.Evento", "Evento")
                        .WithMany("Boletos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AuditorioTickets.Api.Domain.Evento", b =>
                {
                    b.Navigation("Boletos");
                });
#pragma warning restore 612, 618
        }
    }
}
